In [1]:
import torch
print(torch.__version__)

2.6.0+cpu


# Создание тензоров

## При помощи функции `arange`

In [3]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
z = torch.arange(2, 10, 2)
z

tensor([2, 4, 6, 8])

In [23]:
# Определяем, где размещен тензор: на cpu или gpu
x.device

device(type='cpu')

In [5]:
x.shape

torch.Size([12])

## При помощи функции `Tensor`

In [18]:
# Тензор - скаляр
y = torch.Tensor([1])
y

tensor([1.])

In [19]:
y.shape

torch.Size([1])

In [20]:
# Питоновский список
lst = [[x, x**2, x**3] for x in range(12)]
lst

[[0, 0, 0],
 [1, 1, 1],
 [2, 4, 8],
 [3, 9, 27],
 [4, 16, 64],
 [5, 25, 125],
 [6, 36, 216],
 [7, 49, 343],
 [8, 64, 512],
 [9, 81, 729],
 [10, 100, 1000],
 [11, 121, 1331]]

In [22]:
type(lst)

list

In [ ]:
# Создаем тензор - двухмерный массив из питоновксого списка:
xx = torch.Tensor([[x, x**2, x**3] for x in range(12)])
xx

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.0000e+00, 1.0000e+00, 1.0000e+00],
        [2.0000e+00, 4.0000e+00, 8.0000e+00],
        [3.0000e+00, 9.0000e+00, 2.7000e+01],
        [4.0000e+00, 1.6000e+01, 6.4000e+01],
        [5.0000e+00, 2.5000e+01, 1.2500e+02],
        [6.0000e+00, 3.6000e+01, 2.1600e+02],
        [7.0000e+00, 4.9000e+01, 3.4300e+02],
        [8.0000e+00, 6.4000e+01, 5.1200e+02],
        [9.0000e+00, 8.1000e+01, 7.2900e+02],
        [1.0000e+01, 1.0000e+02, 1.0000e+03],
        [1.1000e+01, 1.2100e+02, 1.3310e+03]])

In [17]:
# Размерность тензора
xx.shape

torch.Size([12, 3])

## Изменение формы тензоров

In [24]:
x.shape

torch.Size([12])

In [25]:
x.view((3, 4))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [26]:
x.view((-1, 4))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [30]:
x.view((-1, 4)).shape

torch.Size([3, 4])

In [28]:
x.view((2, -1, 2))

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]])

In [29]:
x.view((2, -1, 2)).shape

torch.Size([2, 3, 2])

### Свойства функции `view`
Данные тезноза, полученного с помощью этой функции связаны с данными сиходного тензора:

In [32]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
x1 = x.view((-1, 4))
x1

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [37]:
# Изменим значения в исходном тензоре x:
x[0:4] = -1
x

tensor([-1, -1, -1, -1,  4,  5,  6,  7,  8,  9, 10, 11])

In [38]:
# Соответствующие значения тензора x1 тоже изменились:
x1

tensor([[-1, -1, -1, -1],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

### Свойства функции `reshape`
Может работать с тензорами, которые находятся в разных областях памяти

In [42]:
x2 = x.reshape((3, 4))
x2

tensor([[ 5,  5,  5,  5],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [47]:
x[:4] = -10
x

tensor([-10, -10, -10, -10,   4,   5,   6,   7,   8,   9,  10,  11])

In [48]:
x2

tensor([[-10, -10, -10, -10],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]])

## Функции `zeros` и `ones`

In [51]:
torch.zeros(2, 3, 4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [52]:
torch.ones(2, 3, 4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

## Создание тензоров, заполненных случайными значениями

In [55]:
# Случайные значения имеют равномерное распраделение
torch.rand(2, 3, 4)

tensor([[[0.3969, 0.2558, 0.6099, 0.2916],
         [0.8056, 0.9374, 0.4516, 0.5023],
         [0.2980, 0.1554, 0.5496, 0.6444]],

        [[0.0881, 0.6199, 0.6034, 0.1069],
         [0.7346, 0.9220, 0.3243, 0.8275],
         [0.3280, 0.3111, 0.5717, 0.6857]]])

In [56]:
# Случайные значения имеют нормальное распределение
torch.randn(2, 3, 4)

tensor([[[-1.0545,  1.6469, -1.7846,  0.6192],
         [ 1.0020, -1.1584, -0.2215, -0.2777],
         [-1.1571, -0.0354,  1.6334,  1.0881]],

        [[-0.9718, -0.5595,  2.4430,  0.3991],
         [-1.1544, -2.0468,  0.6902, -1.3541],
         [ 0.1678, -1.0551,  0.6915, -0.0802]]])

# Операции над тензорами

## Арифметические опарации

In [59]:
x = torch.tensor([1., 2., 4., 8.])
y = torch.ones_like(x) * 2
print('x=', x)
print('y =', y)
print('x + y =', x + y)
print('x - y =', x - y)
print('x * y =', x * y)
print('x / y =', x / y)


x= tensor([1., 2., 4., 8.])
y = tensor([2., 2., 2., 2.])
x + y = tensor([ 3.,  4.,  6., 10.])
x - y = tensor([-1.,  0.,  2.,  6.])
x * y = tensor([ 2.,  4.,  8., 16.])
x / y = tensor([0.5000, 1.0000, 2.0000, 4.0000])


In [60]:
x.exp()

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

## Матричные операции

### Матричное умножение

In [62]:
x = torch.arange(12).reshape((3, 4))
y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.mm(x, y.T)

tensor([[ 18,  20,  10],
        [ 58,  60,  50],
        [ 98, 100,  90]])

### Конкатенация

In [63]:
torch.cat((x, y), dim=0)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 2,  1,  4,  3],
        [ 1,  2,  3,  4],
        [ 4,  3,  2,  1]])

In [64]:
torch.cat((x, y), dim=1)

tensor([[ 0,  1,  2,  3,  2,  1,  4,  3],
        [ 4,  5,  6,  7,  1,  2,  3,  4],
        [ 8,  9, 10, 11,  4,  3,  2,  1]])

### Побучение булевых тензоров

In [65]:
x <= y

tensor([[ True,  True,  True,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [66]:
(x <= y).int()

tensor([[1, 1, 1, 1],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

### Суммирование элементов тензора

In [73]:
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [67]:
x.sum()

tensor(66)

In [68]:
# Преобразование результата в скаляр
x.sum().item()

66

In [69]:
# Суммирование вдоль определенных осей
x.sum(dim=0)

tensor([12, 15, 18, 21])

In [72]:
x.sum(dim=0, keepdim=True)

tensor([[12, 15, 18, 21]])

In [70]:
x.sum(dim=1)

tensor([ 6, 22, 38])

In [75]:
x.sum(dim=1, keepdim=True)

tensor([[ 6],
        [22],
        [38]])

## Преобразование типов данных

In [77]:
x.dtype

torch.int64

In [81]:
# Функция преобразования в число с плавающей точной
x.double()

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=torch.float64)

In [80]:
# Универсальная функция преобразования типа
x.type('torch.DoubleTensor')

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=torch.float64)

## Операции над тензорами разных размеров

In [108]:
# Простейший вариант - операции со скаляром:
x = torch.tensor([4, 5, 6, 7])
y = 3
x - y

tensor([1, 2, 3, 4])

### Broadcast

In [110]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(4).reshape((1, 4))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1, 2, 3]]))

In [111]:
a + b

tensor([[0, 1, 2, 3],
        [1, 2, 3, 4],
        [2, 3, 4, 5]])

## Изменение количества осей тензора

In [88]:
x = torch.arange(12).view((-1, 4))
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [89]:
x.shape

torch.Size([3, 4])

In [94]:
# Добавим единичное измерение на позицию 0:
x.unsqueeze(0)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]])

In [95]:
x.unsqueeze(0).shape

torch.Size([1, 3, 4])

In [93]:
# Добавим единичное измерение на позицию 1:
x.unsqueeze(1)

tensor([[[ 0,  1,  2,  3]],

        [[ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11]]])

In [92]:
x.unsqueeze(1).shape

torch.Size([3, 1, 4])

In [96]:
x.unsqueeze(2)

tensor([[[ 0],
         [ 1],
         [ 2],
         [ 3]],

        [[ 4],
         [ 5],
         [ 6],
         [ 7]],

        [[ 8],
         [ 9],
         [10],
         [11]]])

In [97]:
x.unsqueeze(2).shape

torch.Size([3, 4, 1])

In [ ]:
# Добавление единичных измерений:
x.unsqueeze(2).unsqueeze(1).shape

torch.Size([3, 1, 4, 1])

In [100]:
# Удаление единичных измерений:
x.unsqueeze(2).unsqueeze(1).squeeze().shape

torch.Size([3, 4])

## Поворот тензора

### Транспонирование

In [101]:
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [102]:
x.T

tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])

### Использование функции `permute`

In [103]:
x.permute(1, 0)

tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])

In [104]:
xx = torch.rand((2, 3, 4))
xx

tensor([[[0.2318, 0.9774, 0.8097, 0.6813],
         [0.4211, 0.0411, 0.8964, 0.7071],
         [0.9732, 0.4665, 0.1941, 0.2308]],

        [[0.6663, 0.8879, 0.5140, 0.6489],
         [0.3620, 0.0831, 0.9043, 0.3504],
         [0.0724, 0.1565, 0.6088, 0.0368]]])

In [105]:
xx.shape

torch.Size([2, 3, 4])

In [106]:
xx.permute(1, 2, 0)

tensor([[[0.2318, 0.6663],
         [0.9774, 0.8879],
         [0.8097, 0.5140],
         [0.6813, 0.6489]],

        [[0.4211, 0.3620],
         [0.0411, 0.0831],
         [0.8964, 0.9043],
         [0.7071, 0.3504]],

        [[0.9732, 0.0724],
         [0.4665, 0.1565],
         [0.1941, 0.6088],
         [0.2308, 0.0368]]])

In [107]:
xx.permute(1, 2, 0).shape

torch.Size([3, 4, 2])

## Индексирование

In [114]:
x = torch.randn((3, 4))
x

tensor([[ 1.6899,  0.7954, -0.8797,  1.1912],
        [-0.0239,  0.0406, -0.7451, -0.3628],
        [-0.0041,  1.4866,  0.7202,  0.4769]])

In [116]:
x[1:3, 1:3]

tensor([[ 0.0406, -0.7451],
        [ 1.4866,  0.7202]])

In [119]:
x[1:3, 2:3] = 3
x

tensor([[ 1.6899,  0.7954, -0.8797,  1.1912],
        [-0.0239,  0.0406,  3.0000, -0.3628],
        [-0.0041,  1.4866,  3.0000,  0.4769]])

In [121]:
x[:2, :] = 1
x

tensor([[ 1.0000,  1.0000,  1.0000,  1.0000],
        [ 1.0000,  1.0000,  1.0000,  1.0000],
        [-0.0041,  1.4866,  3.0000,  0.4769]])

## Преобразование в `numpy` и обратно

In [122]:
x

tensor([[ 1.0000,  1.0000,  1.0000,  1.0000],
        [ 1.0000,  1.0000,  1.0000,  1.0000],
        [-0.0041,  1.4866,  3.0000,  0.4769]])

In [124]:
y = x.numpy()
y

array([[ 1.        ,  1.        ,  1.        ,  1.        ],
       [ 1.        ,  1.        ,  1.        ,  1.        ],
       [-0.00413207,  1.4866263 ,  3.        ,  0.4768925 ]],
      dtype=float32)

In [125]:
y = torch.tensor(y)
y

tensor([[ 1.0000,  1.0000,  1.0000,  1.0000],
        [ 1.0000,  1.0000,  1.0000,  1.0000],
        [-0.0041,  1.4866,  3.0000,  0.4769]])